### ISSUE TITLE
Lexification operator '#' not supported

### ISSUE THREAD

**Issue by stlutz** [hpi-swa/Ohm-S#35]
[Lexification](https://github.com/harc/ohm/blob/master/doc/syntax-reference.md#lexification-) currently seems to not be supported. Trying to create a grammar using this operator fails, throwing an `OhmMatchFailure`.

**Comment by codeZeilen** [comment]
Interesting issue. We do not have the operator as we do not restrict the usage of rules. However, by not providing it you now can not use grammars interchangeably. I will add the syntax without any semantic as a first step.

**Comment by codeZeilen** [comment]
I just realized that everything is already in place for it. Just the boostraping process used an old definition...

**Comment by codeZeilen** [comment]
You will have to pull the most recent version and execute:

```Smalltalk
OhmGrammarOfOhm recompile
```
