### ISSUE TITLE
BinarySelectorChar in OhmExplicitSendsSmalltalk

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa/Ohm-S#45]
The Expression `3-6` is evaluated to normalFloatingPointLiteral_exponent. It seems to be an issue of the grammar of the `binaryMessageSelectorChar`.

It would make the stiling with OmegaPrint correct in the case of using '-' as BinaryMessage. [Here you can see a picture of how it is formatted right now.](https://github.com/hpi-swa-teaching/OhmPrettyPrint/issues/55)
Thank you.

**Comment by codeZeilen** [comment]
Good catch. I am on it :)
