### ISSUE TITLE
OhmExplicitSendsSmalltalk has only OperandCascades

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa/Ohm-S#46]
Matching something like `self new test; test` it is matched as OperandCascade with `self` as operand and `new test` and `test` as MessageChains. I was wondering whether that should be an UnaryCascade.

In case it shouldn't. What is an UnaryCascade and what a BinaryCascade? I can't find an example that is matched as one of those.

**Comment by codeZeilen** [comment]
`self new test; test`

Should be a unary cascade, as it is a cascade of messages send to the result of a unary message send. I will see to it.

**Comment by codeZeilen** [comment]
Fixed in 589dc09b
