### ISSUE TITLE
BinaryCascade in latest fix

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa/Ohm-S#49]
In the latest commit from 07.07.2020 binary cascades are again matched as operand cascades.

We tried matching `1 + 2 negated; negated` which was in the commit from 06.07.2020 matched as binaryCascade and in the commit from 07.07.2020 it is matched as operandCascade from `OhmExplicitSendsSmalltalk`.

**Comment by codeZeilen** [comment]
I looked into it and currently I think that this is actually correct to parse it as a binary cascade:

```Smalltalk
1 + 5 negated; negated
"corresponds to"
1
  + 5 negated;
  negated
"print it ->"
-1
```

Which is different from the unary message cascade case:

```Smalltalk
self new test; test
"corresponds to"
self new
  test;
  test
```

**Comment by Paula-Kli** [comment]
Yes and in your commit  from [06.07.](https://github.com/hpi-swa/Ohm-S/commit/0ae57805d3055fe9acafb17f45315410343bce55) this works perfectly fine.

But in your updated version inspecting the cst I get this result:

![grafik](https://user-images.githubusercontent.com/49535291/87178614-b5178580-c2dd-11ea-83ea-9da7feebfe7c.png)

I am starting to parse at the Rule Expression but this shouldn't make a difference right?

**Comment by codeZeilen** [comment]
Ah oops. I meant it is correct to parse it as an OperandCascade. The receiver of the #+ is the 1, the argument is `5 negated`. Does it make a great difference for printing?

**Comment by Paula-Kli** [comment]
Ah ok I see! Thanks for clarifying that!
I think we will ask our customer about it ;)

What is a binaryCascade then?

**Comment by codeZeilen** [comment]
An example for a binary cascade would be: 

```Smalltalk
1 + 2 
  raised to: 10;
  yourself
```

In this case the receiver is the BinaryMessageSend `1 + 2`.

**Comment by Paula-Kli** [comment]
Ah alright!

Thanks a lot!! That explains it! In that case it works fine ;)
