### ISSUE TITLE
FindFirst:startingAt: not understood

### ISSUE THREAD

**Issue by Paula-Kli** [hpi-swa/Ohm-S#54]
The Method `FindFirst:startingAt:` is not in the package. It is easy to implement it yourself in your local image but at first is missing.

Also your CI fails due to that ;)

**Comment by felixauringer** [comment]
You can see the error log [here](https://travis-ci.org/github/hpi-swa/Ohm-S/builds/707564735).

**Comment by codeZeilen** [comment]
Finally fixed in f7d2fd760739674d6c31d3c5e29556e2b43aa14f
