### ISSUE TITLE
Grammars reference parsing state of previous parse operations

### ISSUE THREAD

**Issue by stlutz** [hpi-swa/Ohm-S#66]
While looking at the objects flying through my image, I noticed that Ohm keeps a lot more of its objects referenced than I would have expected.

<details>
<summary>With 12 grammars (most of them never used), the total tally is over 120,000 objects</summary>

| Class | Instances |
| ---: | :--- |
 | OhmPExprApply | 27212 | 
 | OhmPExprString | 19580 | 
 | OhmPExprSeq | 12372 | 
 | OhmFailureDescriptor | 11456 | 
 | OhmInterval | 9090 | 
 | OhmNode | 9090 | 
 | OhmPExprAlt | 6791 | 
 | OhmInputMemoizedResult | 6724 | 
 | OhmParsingState | 6380 | 
 | OhmPExprNot | 5236 | 
 | OhmPositionInfo | 2285 | 
 | OhmPExprRange | 2176 | 
 | OhmPExprMany | 1723 | 
 | OhmPExprOpt | 1283 | 
 | OhmRuleDefine | 281 | 
 | OhmPExprAnything | 197 | 
 | OhmRuleInline | 117 | 
 | OhmPExprLookahead | 109 | 
 | OhmPExprParam | 15 | 
 | OhmGrammar | 12 |

</details>

Most notably to me, however, were the thousands of `OhmFailureDescriptor` instances. Why would we ever need to hold on to those?

<details>
<summary>It seems like every rule body holds onto parsing state from previous parsing operations.</summary>

![image](https://user-images.githubusercontent.com/24944129/115115330-3c440900-9f94-11eb-9767-660dfd2b3576.png)

</details>

My assumption would be that `OhmPExprApply` does (erroneously?) not release its `cachedRuleBodyGrammar`.
Still, this might actually be intended behavior. I am not certain, but wanted to make sure either way.

**Comment by codeZeilen** [comment]
One thing that was cached until today were the OhmSyntaxTestCase results. That was a remnant from Gramada that was, in addition, implemented in a suboptimal way. I removed it in b329bc051c4cd

You might be very much right about the unreleased `cachedRuleBodyGrammar`. Will look into it. :)

**Comment by codeZeilen** [comment]
Hm. The code already contained the solution just not in finished form :) The representation of the parsing process is now an empty token Object.

**Comment by codeZeilen** [comment]
@stlutz If you could check how your system behaves after merging these changes, we might close this issue directly again. :)
